visevol/Cscope

- Backend/Dockerfile
- Backend/resources/requirements.txt
- README.md
- compose.yml
Fixes: #2 
I updated the Dockerfile of the backend service, and I added a docker compose file at the root of the project so that both services can be started at the same time with a simple command. I also updated the README at the root of the project to provide instructions.
Reorder Dockerfile instructions to make build time faster when only the
source changes.
Developers can just run this command at the root of the project to
launch both the frontend and backend services:
```
$ docker compose up
```
> Add docker compose file at the root of the project

- api/app/controllers/repositories_controller.rb
- api/app/models/repository.rb
- api/config/routes.rb
- api/db/migrate/20241004015517_create_repositories.rb
- api/db/schema.rb
- api/test/controllers/repositories_controller_test.rb
- api/test/fixtures/repositories.yml
- api/test/models/repository_test.rb
Add the Repository model, powered by the `repositories` table. 
This table contains the high level information of a repository analyzed by the application.
Add the RepositoryController and a route to the `#show` action
> [Backend] Add Repository model & controller

- api/Gemfile
- api/Gemfile.lock
- api/app/controllers/repositories_controller.rb
- api/app/models/remote_repository.rb
- api/app/models/repository.rb
- api/app/services/github_service.rb
- api/config/routes.rb
- api/test/controllers/repositories_controller_test.rb
- api/test/models/remote_repository_test.rb
- api/test/models/repository_test.rb
Fixes: https://github.com/visevol/GihubVisualisation/issues/9
Add #create action to RepositoriesController
The create action responds to: `POST /repositories`, and it expects a
url parameter.
The action will verify that the repository exists on the remote, and if
it does, it will create an entry for this repository in our database.
> [Backend] Add the #create action in RepositoriesController

- api/Gemfile
- api/Gemfile.lock
- api/lib/git_repository.rb
Part of: https://github.com/visevol/GihubVisualisation/issues/10
Add the GitRepository class in the lib directory.
This is a wrapper over the process of cloning and extracting logs from a
git repository.
1. Build the `api` docker container: `docker compose build api`
2. Open a rails command line: `docker compose run api bin/rails c`
3. From this console, you can instantiate the GitRepository class of this PR and play with it:
```ruby
repo = GitRepository.new("https://github.com/rails/rails")
repo.clone
repo.logs do |logs|
logs.each do |line|
p line
end
end
```
^ This clones the https://github.com/rails/rails repository, and dumps the content of all its commits (93 000).
> [Backend] Add GitRepository lib class

- api/app/models/commit.rb
- api/app/models/commit_file_change.rb
- api/db/migrate/20241006232458_create_commits.rb
- api/db/migrate/20241007003949_create_commit_file_changes.rb
- api/db/schema.rb
- api/test/fixtures/commit_file_changes.yml
- api/test/fixtures/commits.yml
- api/test/fixtures/repositories.yml
- api/test/models/commit_file_change_test.rb
- api/test/models/commit_test.rb
Closes: https://github.com/visevol/GihubVisualisation/issues/19
This PR adds two new models: 
- Commit
- CommitFileChange
> [Backend] Add basic repository data model 

- api/Gemfile
- api/Gemfile.lock
- api/app/models/commit.rb
- api/app/models/repository.rb
- api/app/services/repository_sync_service.rb
- api/test/fixtures/repositories.yml
- api/test/models/repository_test.rb
- api/test/services/repository_sync_service_test.rb
- api/test/test_helper.rb
Add the RepositorySyncService class
This class takes a `Repository` model, and sync its content in our database:
1. It clones the repository in a tmp directory
2. It calls `git log` on it, and saves the output in a temporary file.
3. The service read the log files and creates `Commit` and `CommitFileChange` records for each of the commits.
> [Backend] Add RepositorySyncService

- api/lib/tasks/repositories.rake
You can this task to check how long it takes to fully import a repository:
```
$ REPOSITORY_ID=1 bin/rake repositories:benchmark_sync
➜  api git:(zgv/add-task-to-create-repository-from-remote) ✗ REPOSITORY_ID=1 bin/rake repositories:benchmark_sync
deleting commits and file changes of repository: https://github.com/rails/rails...
done.
syncing https://github.com/rails/rails...
Sync duration: 96.967830   4.042393 144.274511 (128.719191)
Commit created: 93158
File changes created: 197661
```
> Add rake task to benchmark a repository sync

- api/lib/git_repository.rb
- api/test/services/repository_sync_service_test.rb
Pass the `--reverse` flag to `git log` inside GitRepository.
This means we now index commits in chronological order. Which means the latest commit is technically always the highest id.
This means:
- `Repository.find(1).commits.last` --> always returns the last commit
- `Repository.find(1).commits.first` --> always returns the first commit
> [Backend] Change the order of commits in GitRepository#logs

- api/Gemfile
- api/Gemfile.lock
- api/app/jobs/repository_sync_job.rb
- api/config/database.yml
- api/config/environments/development.rb
- api/config/routes.rb
- api/db/queue_schema.rb
- api/db/seeds.rb
- api/test/jobs/repository_sync_job_test.rb
Closes: https://github.com/visevol/GihubVisualisation/issues/12
This PR setups [solid_queue ](https://github.com/rails/solid_queue)for development.
It also adds the [`mission_control-jobs`](https://github.com/rails/mission_control-jobs) gem, and mount the routes of that gem whenever rails is in the `development` environment.
Finally, it adds the `RepositorySyncJob`, which is just a job that wraps the execution of the `RepositorySyncService`.
You can enqueue the job like this:
```
RepositorySyncJob.perform_later(repository_id: 1)
```
> [Backend] Add `RepositorySyncJob`

- api/app/models/repository.rb
- api/test/models/repository_test.rb
Closes: https://github.com/visevol/GihubVisualisation/issues/13
Whenever a Repository is created, a RepositorySyncJob is automatically enqueued.
> [Backend] Enqueue a `RepositorySyncJob` on Repository creation

- api/app/models/repository.rb
- api/db/migrate/20241011035221_add_unique_index_on_repository_domain_and_path.rb
- api/db/schema.rb
- api/test/models/repository_test.rb
Closes: https://github.com/visevol/GihubVisualisation/issues/16
This PR adds a validation that prevents the creation of duplicated `Repository` on the same domain. 
For example:
```ruby
Repository.create!(name: "duplicated_repo", domain: "github.com", path: "/example/duplicated_repository")
Repository.create!(name: "duplicated_repo", domain: "github.com", path: "/example/duplicated_repository")
Repository.create!(name: "duplicated_repo", domain: "github.com", path: "/example/duplicated_repository")
Repository.create!(name: "duplicated_repo", domain: "gitlab.com", path: "/example/duplicated_repository")
```
> [Backend] Prevent creation of duplicated repositories on the same domain

- api/app/models/commit.rb
- api/app/models/source_file.rb
- api/app/models/source_file_change.rb
- api/app/services/repository_sync_service.rb
- api/db/migrate/20241013004144_add_association_between_source_files_and_source_file_changes.rb
- api/db/schema.rb
- api/lib/tasks/repositories.rake
- api/test/fixtures/source_file_changes.yml
- api/test/services/repository_sync_service_test.rb
Closes: https://github.com/visevol/GihubVisualisation/issues/29
Connect the `source_files` table with `source_file_changes`. With this change, `source_file_changes` is now a join table between commits and source files.
Add new associations so expressions like these are possible:
```ruby
repository = Repository.find_by(name: "rails")
initial_commit = repository.commits.first
initial_commit.source_files.count # number of files affected by the initial commit
=> 295
gemfile = repository.source_files.find_by(filepath: "Gemfile")
gemfile.commits.count # number of commits that modifies the Gemfile
=> 879
```
> [Backend] Connect the `source_files` table with `source_file_changes` 

- api/app/models/source_file_change.rb
- api/db/migrate/20241013193116_add_unique_index_on_source_file_change.rb
- api/db/schema.rb
- api/db/seeds.rb
- api/test/models/source_file_change_test.rb
A commit can only change a file in one way.
For example, It does not make sense to say:
- Commit "abcdef" changes file A by adding 2 lines
- Commit "abcdef" changes file A by adding 5 lines
Instead, we say:
- Commit "abcdef" changes file A by adding 7 lines
This prevents recording multiple source file changes for the same file
on a given commit.
> [Backend] Add uniqueness constraint on SourceFileChange

- api/app/models/source_file_change.rb
- api/app/services/repository_sync_service.rb
- api/db/migrate/20241013222300_add_for_changes_ledger_to_commits.rb
- api/db/schema.rb
- api/lib/git_repository.rb
- api/test/services/repository_sync_service_test.rb
The `changes ledger` is a set of commits in which it's safe to sum their `source_file_changes` to get an accurate representation of the state of the repository at a given revision.
This PR:
- adds a `for_changes_ledger` column on commits.
- update the RepositorySyncService so that it generates the changes ledger on top of the commit history. 
- commits part of that ledger are tagged by setting their `for_changes_ledger` to `true`.
This new concept allows us to give the `line_count` of a `source_file`, at any revision.
> [Backend] Tag commits if they are part of the `changes ledger`

- api/app/models/commit.rb
- api/app/models/source_file.rb
- api/app/models/source_file_change.rb
- api/test/fixtures/commits.yml
- api/test/fixtures/repositories.yml
- api/test/fixtures/source_file_changes.yml
- api/test/fixtures/source_files.yml
- api/test/models/source_file_test.rb
Implement SourceFile#line_count
The #line_count method returns the line count of the file.
The method accepts a `revision_id` kwargs, which is the id of a commit
you're targetting. When provided, the method will output the line count
of the file at that revision.
> [Backend] Implement the `#line_count` method on `SourceFile` 

- api/app/services/gitland/commands/list_tree_with_line_numbers.rb
- api/app/services/gitland/repository.rb
Change the LsTree Gitland command so that it list the file tree with the line number of each file, instead of the size of each file.
Apparently, the `4b825dc642cb6eb9a060e54bf8d69288fbee4904` hash represents an empty directory in Git. 
This means we can diff the current repository with this hash to get the diff of line numbers for each file. Because the `4b825dc642cb6eb9a060e54bf8d69288fbee4904` represents an empty directory, by definition the added lines in the diff is the line number of that file.
> [Backend] Implement a Gitland command that returns the file listing of a repository with the with line count

- api/app/controllers/trees_controller.rb
- api/config/routes.rb
- api/test/controllers/trees_controller_test.rb
Closes: https://github.com/visevol/GihubVisualisation/issues/42
This controller can be used to find all files on a repository, with their line numbers.
Usage:
```
GET /repositories/3/tree/head
```
returns:
```json
[{"filepath":".formatter.exs","line_count":4},{"filepath":".gitignore","line_count":24},{"filepath":"LICENSE.txt","line_count":21},{"filepath":"README.md","line_count":32},{"filepath":"amqp/amqp-xml-doc0-9-1.pdf","line_count":0},{"filepath":"amqp/amqp0-9-1.pdf","line_count":0},{"filepath":"amqp/amqp0-9-1.stripped.xml","line_count":459},{"filepath":"amqp/amqp0-9-1.xml","line_count":2843},{"filepath":"config/config.exs","line_count":30},{"filepath":"examples/.gitignore","line_count":1},{"filepath":"examples/README.md","line_count":12},{"filepath":"examples/requirements.txt","line_c …
```
> [Backend] Add the trees controller

- api/app/controllers/files_controller.rb
- api/app/models/source_file.rb
- api/config/routes.rb
- api/test/controllers/files_controller_test.rb
- api/test/controllers/trees_controller_test.rb
- api/test/models/source_file_test.rb
Part of https://github.com/visevol/GithubVisualisation/issues/41
Add a FilesController.
This controller returns information about a file on a repository.
Right now, it only returns the following information:
- filepath
- commits count
- main contributor
Example:
```
GET /repositories/123/files/head/activejob/lib/active_job.rb
{
filepath: "activejob/lib/active_job.rb",
commits_count: 75,
main_contributor: {
author: "Ryuta Kamizono",
commits_count: 7
}
}
```
> [Backend] Add the FilesController

- api/app/models/source_file.rb
- api/test/controllers/files_controller_test.rb
- api/test/models/source_file_test.rb
Closes: https://github.com/visevol/GithubVisualisation/issues/53
Only count non merge commits in SourceFile#main_contributor.
> [Backend] Fix SourceFile#main_contributor

- api/app/controllers/commits_controller.rb
- api/app/services/repository_statistics_service.rb
- api/config/routes.rb
- api/db/migrate/20241020003703_add_index_on_commits_committer_date.rb
- api/db/schema.rb
- api/test/controllers/commits_controller_test.rb
- api/test/fixtures/commits.yml
Part of https://github.com/visevol/GithubVisualisation/issues/50
Add a controller action that returns data points that describes a stream of commit over time. Each data point is a date, and a description of what changed that date.
Example:
```
GET /repositories/123/commits/stats/commits_over_time
[
{ 
date: "2010-01-01", 
commit_counts: 6,
modified_lines: 49, 
modified_files: 13,
},
...
]
```
> [Backend] Add `CommitsController` and `#commits_over_time` action

- api/app/controllers/commits_controller.rb
- api/app/services/repository_statistics_service.rb
- api/test/controllers/commits_controller_test.rb
Add date filtering on the CommitsController#commits_over_time action. Requests can now include a `start_date` and `end_date` url parameter to filter the data points.
Example:
```
GET /repositories/123/commits/stats/commits_over_time?start_date=2023-01-01
[
{ 
date: "2023-01-01", 
commit_counts: 6,
modified_lines: 49, 
modified_files: 13,
},
... only data point after 2023-01-01
]
```
```
GET /repositories/123/commits/stats/commits_over_time?end_date=2020-01-01
[
... only data point before 2020-01-01
{ 
date: "2020-01-01", 
commit_counts: 6,
modified_lines: 49, 
modified_files: 13,
},
]
```
```
GET /repositories/123/commits/stats/commits_over_time?start_date=2020-01-01&end_date=2021-01-01
[
... only data point between 2020-01-01 and 2021-01-01
]
```
> [Backend] Add date filtering on commits over time endpoint

- api/app/services/gitland/commands/log.rb
- api/test/services/gitland/commands/log_test.rb
TL;DR This command wraps the execution of `git log` on a repository.
Related to https://github.com/visevol/GithubVisualisation/issues/57, first iteration at trying to remove `/lib/git_repository.rb`. 
The RepositorySyncService depends on `lib/git_repository.rb` to generate a log file for a repository. I'm adding a Gitland command to interface `git log` so that RepositorySyncService can use Gitland instead.
> [Backend] Add Gitland::Commands::Log

- api/app/jobs/initialize_gitland_repository_job.rb
- api/app/jobs/initialize_repository_job.rb
- api/app/models/repository.rb
- api/test/jobs/initialize_gitland_repository_job_test.rb
- api/test/jobs/initialize_repository_job_test.rb
- api/test/models/repository_test.rb
Rename `InitializeGitlandRepositoryJob` to `InitializeRepositoryjob`.
The job now:
- clone the repository
- sync the repository
> [Backend] Change job enqueueing logic when a repo is created

- api/app/services/gitland/commands/diff.rb
- api/app/services/gitland/repository.rb
- api/test/services/gitland/commands/diff_test.rb
- api/test/services/gitland/repository_test.rb
This method returns the number of line for a specific file.
> [Backend] Add #file_line_count to Gitland::Repository

- api/app/controllers/files_controller.rb
- api/app/models/source_file.rb
- api/test/controllers/files_controller_test.rb
- api/test/models/source_file_test.rb
Add the line_count in the response of `FilesController#show`:
> [Backend] Add line_count to output of FilesController#show

- api/app/controllers/commits_controller.rb
- api/app/services/repository_statistics_service.rb
- api/test/controllers/commits_controller_test.rb
The endpoint now returns the number of added and removed lines per date, rather than a number of lines change.
This gives more freedom to the frontend so that it can render different views with the same data set.
Example:
> [Backend] Update api schema of `#commits_over_time` endpoint

- api/app/controllers/files_controller.rb
- api/app/models/source_file.rb
- api/test/controllers/commits_controller_test.rb
- api/test/controllers/files_controller_test.rb
- api/test/fixtures/commits.yml
- api/test/fixtures/source_file_changes.yml
- api/test/models/source_file_test.rb
Part of https://github.com/visevol/GithubVisualisation/issues/41
This PR surfaces the `creation_date` and the `last_modification_date` of a file in the response of:
```
GET /repositories/1/files/head/activejob/lib/active_job.rb
```
Example:
Add new methods to SourceFile model
Add the `#creation_date` method. It returns the date of the commit that
introduces this file.
Add the `#last_modification_date` method. It returns the date of the
last commit that modifies that file.
---
Update FilesController#show action
Show the creation_date and last_modification_date of files in the
response of `FilesController#show` action.
> [Backend] Add `creation_date` and `last_modification_date` to the response of `FilesController#show`

- api/lib/file_classifier.rb
- api/test/lib/file_classifier_test.rb
Base to start categorizing source files.
The classifier accepts a filepath, and returns information about that filepath. For example, its extension and its file type.
> [Backend] Add file classifier class

- api/app/services/gitland/commands/log.rb
- api/test/services/gitland/commands/log_test.rb
We forgot to use the `--no-renames` flag on the `git log` command. This means we were indexing soruce files with weird filepath.
Example:
We were creating source files with this filepath:
```
examples/{tutorial_1_hello_world.py => tutorial_1_hello_world/send.py}
```
instead of:
```
examples/tutorial_1_hello_world/send.py
```
> Fix bug with the Gitland log command

- api/app/services/repository_sync_service.rb
- api/test/services/repository_sync_service_test.rb
Closes: https://github.com/visevol/GithubVisualisation/issues/76
Fix bug where binary files were not picked up by the repository sync service. These files were never synced to our database.
> [Backend] Fix bug where RepositorySyncService don't sync binary files. 

- api/app/models/repository.rb
- api/app/services/gitland/repository.rb
- api/test/models/repository_test.rb
- api/test/services/gitland/repository_test.rb
Add a callback that will remove the local disk copy of the repository whenever a `Repository` gets destroyed.
> [Backend] Remove Gitland repository from disk when a Repository is destroyed. 

- api/app/controllers/files_controller.rb
- api/test/controllers/files_controller_test.rb
Add the `filetype` to the response of the `FileController#show` action
> [Backend] Add `filetype` to the FileController#show response

- api/app/controllers/repositories_controller.rb
- api/app/models/remote_repository.rb
- api/app/models/repository.rb
- api/config/routes.rb
- api/documentation/endpoints.md
- api/test/controllers/repositories_controller_test.rb
- api/test/models/remote_repository_test.rb
Closes: https://github.com/visevol/Cscope/issues/11
The #search action searches a repository by remote url by checking if we have a record of the repository in our database, but also on the remote.
> [Backend]  Add #search endpoint on RepositoriesController

- api/Gemfile
- api/Gemfile.lock
- api/config/initializers/cors.rb
- frontend/.env.development
- frontend/package-lock.json
- frontend/package.json
- frontend/src/api/index.ts
- frontend/src/api/repositories.ts
- frontend/src/components/AddRepository.tsx
- frontend/src/models/remoteRepository.ts
- frontend/src/models/repository.ts
Closes: https://github.com/visevol/Cscope/issues/90
**NOTE** This PR is based on top of https://github.com/visevol/Cscope/pull/92. Make sure to merge that PR first.
Update AddRepository component
Change the form action in AddRepository.tsx to make a request to the
repository search API endpoint.
If the repository exists in our database, we navigate to
`/repository/:repository_id/change-volume`.
If the repository exists on the remote, but not in our database, we show
an alert to the user that the repository exists, but not yet analyzed.
If the repository does not exists anywhere, we just mention that to the
user.
---
Both the API and the create-react-app dev server runs on port 3000. So I also changed the port of the react dev server to 4000 to avoid conflicts.
> [Frontend] Update the `startProjectPage` in the frontend to search repositories by url

- api/app/controllers/application_controller.rb
- api/app/controllers/commits_controller.rb
- api/app/controllers/files_controller.rb
- api/app/services/repository_statistics_service.rb
- api/config/routes.rb
- api/test/controllers/files_controller_test.rb
added the data in this format to keep naming consistency:
```
export interface FileModified {
filepath: string;
total_additions: number;
total_deletions: number;
total_modifications: number;
}
```
It can take a while to compute this information for the entire timeline of the repository (like 30 seconds which is pretty quick for that magnitude of information), else just specify a start_date and/or an end_date.
An interesting thing to note is the filepath shows when a file is renamed/moved to another directory which can be very useful for the other chart.
> added route for bubble chart data

- api/app/models/repository.rb
- api/app/services/repository_sync_service.rb
- api/db/migrate/20241127042936_add_last_sync_at_on_repositories.rb
- api/db/schema.rb
- api/test/controllers/repositories_controller_test.rb
- api/test/services/repository_sync_service_test.rb
Add a `last_synced_at` column on repositories. This column can be used to indicate the frontend when is the last time a repository was successfully synced. 
I'm also adding this field in the response of `GET /repositories/:id/` endpoint. 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> [Backend] Add `last_synced_at` column on repositories

- api/app/controllers/files_controller.rb
- api/app/services/repository_sync_service.rb
- api/config/routes.rb
- api/lib/file_classifier.rb
- api/test/controllers/files_controller_test.rb
- api/test/lib/file_classifier_test.rb
Add route that returns the file types in the repo
Add a new route that returns the list of file types present on the
repository:
```
GET /repositories/123/files/stats/file_types
[
"ruby",
"typescript",
"markdown",
"yaml",
...
]
```
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> [Backend] Add endpoint to return the list of file types known in the repository

- api/app/services/gitland/commands/log.rb
- api/app/services/gitland/repository.rb
- api/app/services/repository_sync_service.rb
- api/test/services/repository_sync_service_test.rb
Fix a bug where the ledger commits were not extracted during sync.
The sync service runs in two steps:
1. it extracts all commits in the history
2. it extracts "ledger" commits, commits as they appear on the "main"
branch of the repository.
In https://github.com/visevol/Cscope/pull/73, we introduced the concept
of "last known commit" in the RepositorySyncService. The idea is to
start the extraction process from the latest commit in the database.
The bug is that the "last know commit" is fetched in both steps.
On the first step, the last known commit is accurate. For new
repositories, we don't have any commits in our database, so the
`git log` command extracts all commits, and we store this in the
database.
On the second step, the last known commit is fetched again from the database. It …
> [Backend] Fix bug in RepositorySyncService
